# version: '3.8'
#
#services:
#  pgdb:
#    image: postgres:15 # Specify a version to ensure consistency (e.g., postgres:15)
#    container_name: pg_server_api0121
#    ports:
#      - '5550:5432'
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#    volumes:
#
#      - ./docker/pg/postgres.conf:/etc/postgresql/postgresql.conf
#      - ./data/pg:/var/lib/postgresql/data
#    command: postgres -c config_file=/etc/postgresql/postgresql.conf
#    networks:
#      - postgres
#    restart: always
#
#  pgadminFp:
#    container_name: pgadmin_0121
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_SERVER_JSON_FILE: /tmp/.pgadmin/servers.json
#    volumes:
#      - ./data/pgadmin:/tmp/.pgadmin
#    ports:
#      - "${PGADMIN_PORT:-5051}:80"
#    networks:
#      - postgres
#    restart: unless-stopped
#
#  spring-app:
#    build: . #
#    container_name: spring_code_camp
#    ports:
#      - "8081:8081"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://pgdb:5432/${POSTGRES_DB}
#      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
#      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
#      JWT_SECRET: ${JWT_SECRET}
#
#    depends_on:
#      - pgdb # Ensures the PostgreSQL database starts and is available before the Spring app
#    networks:
#      - postgres # Connects the Spring app to the same network as the database
#
#networks:
#  postgres:
#    driver: bridge # Defines the custom network for these services
#
#
#


version: '3.8'

services:
  pgdb:
    image: postgres
    container_name: pg_server_api0121
    ports:
      - '5550:5433'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/pg/postgres.conf:/etc/postgresql/postgresql.conf
      - pg_data:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  pgadminFp:
    container_name: pgadmin_0121
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5051}:80"
    networks:
      - postgres
    depends_on:
      pgdb:
        condition: service_healthy
    restart: unless-stopped

  spring-app:
    build: .
    container_name: spring_code_camp
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pgdb:5433/${POSTGRES_DB}?connectionTimeout=30000
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE: 5
      SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT: 60000
      JWT_SECRET: ${JWT_SECRET}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      pgdb:
        condition: service_healthy
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  pg_data:
  pgadmin_data: